table DimPOLine
	lineageTag: 95740e93-ee36-4047-8a09-2a36691d8e95

	column POLineKey
		dataType: string
		lineageTag: f9d18e23-1dfa-44f3-811a-588cf1b6a1a2
		summarizeBy: none
		sourceColumn: POLineKey

	column BUSINESS_UNIT
		dataType: string
		lineageTag: a93c4cd4-cb42-4f58-95fb-26cc5e1eae76
		summarizeBy: none
		sourceColumn: BUSINESS_UNIT

	column PO_ID
		dataType: string
		lineageTag: 5cfedbaa-9ec4-4abb-8303-2c5affdbd496
		summarizeBy: none
		sourceColumn: PO_ID

	column LINE_NBR
		dataType: int64
		lineageTag: d08f1269-4a47-46dc-be35-dc954c6a57be
		summarizeBy: none
		sourceColumn: LINE_NBR

	column VENDOR_ID
		dataType: int64
		summarizeBy: none
		sourceColumn: VENDOR_ID

	column NAME1
		dataType: string
		summarizeBy: none
		sourceColumn: NAME1

	column DESCRIPTION
		dataType: string
		summarizeBy: none
		sourceColumn: DESCRIPTION

	column PO_STATUS
		dataType: string
		summarizeBy: none
		sourceColumn: PO_STATUS

	column BUDGET_DT
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: BUDGET_DT

	partition DimPOLine = m
		mode: import
		source =
				let
					SourceUrl = "https://d.docs.live.net/eb1a13bb642143af/Paneles/Budget_PowerBI.xlsx",
					Workbook = Excel.Workbook(Web.Contents(SourceUrl), null, true),
					Raw = Workbook{[Item="Encumbrance",Kind="Sheet"]}[Data],
					Headers = Table.PromoteHeaders(Raw, [PromoteAllScalars=true]),
					Selected = Table.SelectColumns(Headers, {"BUSINESS_UNIT","PO_ID","LINE_NBR","VENDOR_ID","NAME1","DESCRIPTION","PO_STATUS","BUDGET_DT"}),
					NonBlank = Table.SelectRows(Selected, each [PO_ID] <> null and Text.Trim(Text.From([PO_ID])) <> "" and [LINE_NBR] <> null),
					Typed = Table.TransformColumnTypes(NonBlank, {{"BUSINESS_UNIT", type text},{"PO_ID", type text},{"LINE_NBR", Int64.Type},{"VENDOR_ID", Int64.Type},{"NAME1", type text},{"DESCRIPTION", type text},{"PO_STATUS", type text},{"BUDGET_DT", type datetime}}),
					Normalized = Table.TransformColumns(Typed, {{"BUSINESS_UNIT", each Text.Trim(Text.From(_)), type text},{"PO_ID", each Text.PadStart(Text.Trim(Text.From(_)),10,"0"), type text}}),
					AddKey = Table.AddColumn(Normalized, "POLineKey", each [BUSINESS_UNIT] & "|" & [PO_ID] & "|" & Text.PadStart(Text.From([LINE_NBR]),6,"0"), type text),
					DistinctRows = Table.Distinct(AddKey, {"POLineKey"})
				in
					DistinctRows
